baseURL = 'https://www.freaksquad.help'
languageCode = 'en-us'
title = 'Freak Squad'
theme = "TatBanTheme2.0"
disqusShortname = 'tatsatb'



[taxonomies]
  category = 'categories'
  tag = 'tags'




[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true # Allow HTML in md files

[menu]
  [[menu.main]]
    name = "Main"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Resources"
    url = "/research/"
    weight = 2
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

    
[module]
  [module.hugoVersion]
    extended = true
    min = "0.60.0"
    max = "0.97.0"   
